### ISSUE TITLE
Compatibility Issue with Stripe Module 3.5

### ISSUE THREAD

**Issue by khalilbensaid96** [headlesscommerce/magento-stripe-graphql#1]
**Description:**

I'm encountering a compatibility issue between magento-stripe-graphql and the latest Stripe module version 3.5.

**Environment:**

Frontend: Vuestorefront with Nuxt.js (Vue.js 2)
Backend: Magento
Payment Modules: stripe/module, stripe/module-payments
Library: magento-stripe-graphql
Problem:

Stripe module 3.3 was previously located in app/code, compatible with magento-stripe-graphql.
Upgrade to Stripe module 3.5 relocates the module to vendor/stripe, causing incompatibility.

**Possible Solutions:**

- Revert Stripe module to 3.3: Remove 3.5 and extract 3.3 to app/code.

- Duplicate vendor/stripe directory: Create a copy in app/code/StripeIntegration.

- Modify headless integration code: Adjust code to reference vendor/stripe.

Questions:

What is the recommended solution to ensure compatibility?
Are there plans to update magento-stripe-graphql to address this issue directly?
Additional Information:

**Magento version:** 2.4.6

Thank you for your assistance!

**Comment by davidwindell** [comment]
Hi @khalilbensaid96, this module is only designed for use with https://github.com/headlesscommerce/vsf-magento-stripe and won't be maintained after the next release as it will no longer be required. See https://github.com/headlesscommerce/vsf-magento-stripe/issues/5
